# Generated by Django 4.2.1 on 2023-05-22 19:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("HomeDashboard", "0002_appliances_housestate_doors_housestate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="housestate",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
