# Generated by Django 4.2.1 on 2023-05-22 19:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("HomeDashboard", "0003_alter_housestate_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="housestate",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
