# Generated by Django 4.2.1 on 2023-05-22 22:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("HomeDashboard", "0004_alter_housestate_timestamp"),
    ]

    operations = [
        migrations.CreateModel(
            name="BedroomLeft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ceilingLight", models.BooleanField(default=False)),
                ("lamp", models.BooleanField(default=False)),
                ("leftWindow", models.BooleanField(default=False)),
                ("topWindow", models.BooleanField(default=False)),
                ("door", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Utilities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "electricityUsed",
                    models.DecimalField(decimal_places=3, default=0, max_digits=9),
                ),
                (
                    "electricityCost",
                    models.DecimalField(decimal_places=3, default=0, max_digits=9),
                ),
                (
                    "waterUsed",
                    models.DecimalField(decimal_places=3, default=0, max_digits=9),
                ),
                (
                    "waterCost",
                    models.DecimalField(decimal_places=3, default=0, max_digits=9),
                ),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
            ],
        ),
        migrations.RemoveField(model_name="doors", name="houseState",),
        migrations.RemoveField(model_name="lights", name="houseState",),
        migrations.RemoveField(model_name="windows", name="houseState",),
        migrations.DeleteModel(name="Appliances",),
        migrations.DeleteModel(name="Doors",),
        migrations.DeleteModel(name="HouseState",),
        migrations.DeleteModel(name="Lights",),
        migrations.DeleteModel(name="Windows",),
    ]
