# Generated by Django 4.2.1 on 2023-05-22 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "HomeDashboard",
            "0005_bedroomleft_utilities_remove_doors_housestate_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Bathroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ceilingLight", models.BooleanField(default=False)),
                ("bathtub", models.BooleanField(default=False)),
                ("sink", models.BooleanField(default=False)),
                ("leftWindow", models.BooleanField(default=False)),
                ("door", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="BedroomMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ceilingLight", models.BooleanField(default=False)),
                ("lamp", models.BooleanField(default=False)),
                ("tv", models.BooleanField(default=False)),
                ("topWindow", models.BooleanField(default=False)),
                ("door", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="BedroomRight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ceilingLight", models.BooleanField(default=False)),
                ("lamp", models.BooleanField(default=False)),
                ("rightWindow", models.BooleanField(default=False)),
                ("topWindow", models.BooleanField(default=False)),
                ("door", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Entrance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ceilingLight", models.BooleanField(default=False)),
                ("leftWindow", models.BooleanField(default=False)),
                ("door", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Garage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ceilingLightLeft", models.BooleanField(default=False)),
                ("ceilingLightRight", models.BooleanField(default=False)),
                ("doorLeft", models.BooleanField(default=False)),
                ("doorRight", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Kitchen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ceilingLight", models.BooleanField(default=False)),
                ("sink", models.BooleanField(default=False)),
                ("stove", models.BooleanField(default=False)),
                ("oven", models.BooleanField(default=False)),
                ("dishwasher", models.BooleanField(default=False)),
                ("microwave", models.BooleanField(default=False)),
                ("door", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="LaundryRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ceilingLight", models.BooleanField(default=False)),
                ("washer", models.BooleanField(default=False)),
                ("dryer", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="LivingRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ceilingLight", models.BooleanField(default=False)),
                ("leftLamp", models.BooleanField(default=False)),
                ("rightLamp", models.BooleanField(default=False)),
                ("tv", models.BooleanField(default=False)),
                ("bottomWindow", models.BooleanField(default=False)),
            ],
        ),
    ]
