# Generated by Django 4.2.1 on 2023-05-24 17:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "HomeDashboard",
            "0006_bathroom_bedroommaster_bedroomright_entrance_garage_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Temperature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currentTemperature",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "targetTemperature",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "dateTime",
                    models.DateTimeField(default=django.utils.timezone.localtime),
                ),
            ],
        ),
    ]
